# Generated by Django 5.0.3 on 2024-06-03 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.author')),
                ('newThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.new')),
            ],
        ),
        migrations.AddField(
            model_name='new',
            name='newAuthor',
            field=models.ManyToManyField(through='simpleapp.NewAuthor', to='simpleapp.author'),
        ),
    ]
